name: Rust CI
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      # - '!master'

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    runs-on: ubuntu-latest
    name: cargo CI
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: install system dependencies
        run: |
          sudo apt update
          sudo apt install libunwind-dev
      - name: get repo
        uses: actions/checkout@v4
      - name: install rust
        uses: dtolnay/rust-toolchain@stable
      - name: install additional rust things
        run: |
          rustup component add rustfmt
          rustup component add clippy
      - name: cargo clippy check
        run: cargo clippy --all-features --all-targets --workspace
      - name: cargo clippy fix
        run: cargo clippy --fix --all-features --all-targets --workspace
      - name: cargo fmt
        run: cargo fmt --all
      - name: cargo test
        run: cargo test --all-features && cargo test --no-default-features
      - name: commit back to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: "ci: automatic Rust CI changes"
